# Generated by Django 3.2.17 on 2023-03-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_name',
            field=models.CharField(default='blank.jpg', max_length=100),
        ),
    ]
