# Generated by Django 3.2.17 on 2023-03-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_name',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blank.jpg', upload_to='uploads/images'),
        ),
    ]
